### ISSUE TITLE
Wrong URL for multisite media upload

### ISSUE THREAD

**Issue by carlalexander** [ymirapp/wordpress-plugin#15]
Reported by @pmgarman

Image uploaded on a multisite install has the wrong URL.

![image](https://github.com/ymirapp/wordpress-plugin/assets/654684/fee4e4b8-e303-4169-9f46-dfa44ee545d7)

`ymir.yml` config used for example:

```yml
id: 810
name: garman-dev
type: bedrock
environments:
  staging:
    architecture: arm64
    php: 8.1
    cache: ymir
    cdn:
      caching: assets
    cron: false
    warmup: false
    database:
      server: ymir
      name: garman_dev_staging
    domain:
      - staging.garman.dev
      - '*.staging.garman.dev'
    build:
      commands:
        - 'sh ./build.sh'
      include:
        - web/app/plugins/cloudflare/config.json
        - web/app/plugins/cloudflare/composer.json
        - web/app/plugins/query-monitor/assets
```
