### ISSUE TITLE
password protected pages are not working on ymir

### ISSUE THREAD

**Issue by selul** [ymirapp/wordpress-plugin#5]
If I'm using a password-protected page on Ymir powered website with caching enabled, each time when I try to add the password and view the page is not working, a blank page is showing up.

### Environment: 

1. Default WordPress site using Bedrock with no plugins and default theme( it can be replicated with any theme)
2. Cloudfront caching enabled, ymir env config: 
```yml 
production:
    build:
      commands:
        - 'composer install --no-dev --ignore-platform-reqs'
    deployment: image
```

### How to replicate: 

1. Add a page
2. Set the page as password-protected https://vertis.d.pr/NzJEDt
3. Logout and view the page ( or use Incognito)
